### ISSUE TITLE
Double view controller load animation when proceeding in workflow with keyboard open

### ISSUE THREAD

**Issue by nick-nallick-wwt** [wwt/Workflow#16] opened 2021-05-04 23:32 UTC
View lifecycle is called only once, but animation occurs twice. This is much less likely to happen if the keyboard is dismissed before proceeding.

https://user-images.githubusercontent.com/83362374/117071581-8515f480-acec-11eb-97ca-e2b9a970bdf5.mov

**Comment by Richard-Gist** [comment] 2021-05-06 00:21
Hey @nick-nallick-wwt ,  I tried to reproduce the issue you have in your video but was unsuccessful.  Something to try would be to manually call pushViewController to see if it happens outside of Workflow.  If you have more details or can create a small code sample for me to see the issue locally, please add them to this issue.

Here's a video of me trying to reproduce in an iPhone 8 simulator with the sample app, and not having success.

https://user-images.githubusercontent.com/79471462/117225068-b4049700-adce-11eb-8d4c-cdcf70f7723b.mov

**Comment by Richard-Gist** [comment] 2021-05-12 17:53
Hey, it's been a week and I haven't seen any responses on this issue.  I'll give to EOD today to respond before I close it.  If you found the fix but cannot close this issue, let me know.

**Comment by Richard-Gist** [comment] 2021-05-13 15:00
Closing as invalid, since we were not able to repro and no further steps were provided.

**Closed by Richard-Gist** 2021-05-13 15:00 UTC
Labels: bug, invalid
